---
#
- include_vars: "{{ansible_os_family}}.yml"
# Install latest wordpress and dependencies
- name: Install | Install dependencies for WordPress
  action: "{{ ansible_pkg_mgr }} state=installed name={{ item }}"
  with_items: wp_packages

- name: Install | Create source directory
  file:
    path={{ item }}
    state=directory
  with_items:
    - "{{wp_source_dir}}"
    - "{{wp_dest_dir}}"

- name: Install | Download Wordpress
  get_url:
    url="https://www.wordpress.org/latest.tar.gz"
    dest="{{ wp_source_dir }}/wordpress.tar.gz"
    validate_certs=no

- name: Install | Extract Wordpress
  unarchive:
    copy=no
    src="{{ wp_source_dir }}/wordpress.tar.gz"
    dest={{ wp_dest_dir }}
    owner={{ wp_owner }}
    group={{ wp_group }}
    creates="{{ wp_dest_dir }}/wordpress"

- name: Install | Change ownership for wp-content directory
  file:
    path="{{ wp_dest_dir }}/wp-content"
    state=directory
    owner={{ wp_owner }}
    group={{ wp_group }}
    mode=0755
